SILENT  = @

all:
	$(SILENT) make -C ..


dofullpdf:
	$(SILENT) make dofullpdf -C ..

dopdflatex:
	$(SILENT) make dopdflatex -C ..

dopdf2ps:
	$(SILENT) make dopdf2ps -C ..

dobibtex:
	$(SILENT) make dobibtex -C ..

domakeidx:
	$(SILENT) make domakeidx -C ..

domakeadx:
	$(SILENT) make domakeadx -C ..

wall: 
	$(SILENT) make wall: -C ..

warntex:
	$(SILENT) make warntex -C ..

warn2do:
	$(SILENT) make warn2do -C ..

warnspell:
	$(SILENT) make warnspell -C ..

summary:
	$(SILENT) make summary -C ..

clean:
	$(SILENT) make clean -C ..

dirk:
	$(SILENT) make dirk -C ..

mauBuild:
	$(SILENT) make mauBuild -C ..

mauClean:
	$(SILENT) make mauClean -C ..

mauCleanAll:
	$(SILENT) make mauCleanAll -C ..
